//! Self-contained interactive HTML report generation.

use crate::analysis::{ComparisonMetrics, ModelMetrics};
use crate::errors::VizError;
use std::path::Path;

/// Generate a self-contained HTML report and write it to `output_path`.
pub fn write_report(
    image_name: &str,
    metrics: &[ModelMetrics],
    comparisons: &[ComparisonMetrics],
    output_path: &Path,
) -> Result<(), VizError> {
    let html = render_html(image_name, metrics, comparisons);
    std::fs::write(output_path, &html)
        .map_err(|e| VizError::Html(format!("Failed to write {}: {e}", output_path.display())))?;
    Ok(())
}

fn render_html(
    image_name: &str,
    metrics: &[ModelMetrics],
    comparisons: &[ComparisonMetrics],
) -> String {
    let metrics_rows = metrics
        .iter()
        .map(|m| {
            format!(
                "<tr><td>{}</td><td>{}/{}</td><td>{}</td><td>{:.2}</td><td>{}</td><td>{:.1}%</td></tr>",
                escape_html(&m.model_name),
                m.effective_rank,
                m.embed_dim,
                m.dead_dimensions,
                m.patch_entropy,
                m.cls_l2_norm.map(|v| format!("{:.1}", v)).unwrap_or("N/A".into()),
                m.top10_variance_pct,
            )
        })
        .collect::<Vec<_>>()
        .join("\n");

    let comparison_rows = comparisons
        .iter()
        .map(|c| {
            format!(
                "<tr><td>{}</td><td>{}</td><td>{}</td><td>{:.3}</td><td>{:.3}</td><td>{:.3}</td></tr>",
                escape_html(&c.model_a),
                escape_html(&c.model_b),
                c.cls_cosine_sim.map(|v| format!("{:.3}", v)).unwrap_or("N/A".into()),
                c.linear_cka,
                c.knn_overlap_k10,
                c.mean_patch_correspondence,
            )
        })
        .collect::<Vec<_>>()
        .join("\n");

    format!(
        r#"<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>latent-inspector: {image_name}</title>
<style>
  body {{ font-family: 'Segoe UI', system-ui, sans-serif; margin: 2rem; background: #0d1117; color: #e6edf3; }}
  h1, h2 {{ color: #79c0ff; }}
  table {{ border-collapse: collapse; width: 100%; margin: 1rem 0; }}
  th {{ background: #161b22; padding: 0.5rem 1rem; text-align: left; color: #79c0ff; border-bottom: 2px solid #30363d; }}
  td {{ padding: 0.4rem 1rem; border-bottom: 1px solid #21262d; }}
  tr:hover td {{ background: #161b22; }}
  .badge {{ font-size: 0.8em; background: #1f6feb; padding: 2px 8px; border-radius: 12px; }}
</style>
</head>
<body>
<h1>latent-inspector</h1>
<p>Image: <code>{image_name}</code></p>

<h2>Per-model metrics</h2>
<table>
  <thead>
    <tr>
      <th>Model</th>
      <th>Repr. rank</th>
      <th>Dead dims</th>
      <th>Patch entropy</th>
      <th>CLS L2 norm</th>
      <th>Top-10 var%</th>
    </tr>
  </thead>
  <tbody>
    {metrics_rows}
  </tbody>
</table>

<h2>Cross-model comparison</h2>
<table>
  <thead>
    <tr>
      <th>Model A</th>
      <th>Model B</th>
      <th>CLS cosine sim</th>
      <th>Linear CKA</th>
      <th>k-NN overlap (k=10)</th>
      <th>Mean patch corr.</th>
    </tr>
  </thead>
  <tbody>
    {comparison_rows}
  </tbody>
</table>

<footer style="margin-top:3rem;color:#8b949e;font-size:0.8em">
  Generated by <a href="https://github.com/AbdelStark/latent-inspector" style="color:#79c0ff">latent-inspector</a>
</footer>
</body>
</html>"#
    )
}

fn escape_html(s: &str) -> String {
    s.replace('&', "&amp;")
        .replace('<', "&lt;")
        .replace('>', "&gt;")
        .replace('"', "&quot;")
}

#[cfg(test)]
mod tests {
    use super::*;
    use tempfile::tempdir;

    #[test]
    fn test_html_contains_title() {
        let html = render_html("test.jpg", &[], &[]);
        assert!(html.contains("test.jpg"));
    }

    #[test]
    fn test_escape_html() {
        assert_eq!(escape_html("<script>"), "&lt;script&gt;");
    }

    #[test]
    fn test_write_report() {
        let dir = tempdir().unwrap();
        let path = dir.path().join("report.html");
        write_report("img.jpg", &[], &[], &path).unwrap();
        let content = std::fs::read_to_string(&path).unwrap();
        assert!(content.contains("<!DOCTYPE html>"));
    }
}
